'use server';

/**
 * @fileOverview Summarizes comments generated by the LLM analysis, either slide-by-slide or overall.
 *
 * - summarizeComments - A function that handles the comment summarization process.
 * - SummarizeCommentsInput - The input type for the summarizeComments function.
 * - SummarizeCommentsOutput - The return type for the summarizeComments function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeCommentsInputSchema = z.object({
  comments: z.array(z.string()).describe('An array of comments to summarize.'),
  summaryType: z
    .enum(['slide-by-slide', 'overall'])
    .describe('The type of summary to generate.'),
  slideTitles: z.array(z.string()).optional().describe('An array of slide titles corresponding to the comments.'),
});
export type SummarizeCommentsInput = z.infer<typeof SummarizeCommentsInputSchema>;

const SummarizeCommentsOutputSchema = z.object({
  summary: z.string().describe('A summary of the comments.'),
});
export type SummarizeCommentsOutput = z.infer<typeof SummarizeCommentsOutputSchema>;

export async function summarizeComments(input: SummarizeCommentsInput): Promise<SummarizeCommentsOutput> {
  return summarizeCommentsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeCommentsPrompt',
  input: {schema: SummarizeCommentsInputSchema},
  output: {schema: SummarizeCommentsOutputSchema},
  prompt: `You are an expert in summarizing feedback and comments on presentations.

  You will receive a list of comments and a summary type. Based on the summary type, you will generate a summary of the comments.

  If the summary type is slide-by-slide, you will generate a summary of the comments for each slide, using the slide titles provided.
  If the summary type is overall, you will generate a single summary of all the comments.

  Comments: {{comments}}
  Summary Type: {{summaryType}}
  Slide Titles: {{slideTitles}}
  `,
});

const summarizeCommentsFlow = ai.defineFlow(
  {
    name: 'summarizeCommentsFlow',
    inputSchema: SummarizeCommentsInputSchema,
    outputSchema: SummarizeCommentsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
